spring:
  application:
    name: demo-receiver
  threads:
    virtual:
      enabled: false


fpb:
  endpoint:
    url: "http://localhost:8080"

configurationFilePath: /home/spacer/.oci/config
pathToSaveFile: /home/spacer/fste1/file

custom:
  proxy:
    uri: "localhost"
    port: "8899"
    username: "client"
    password: "pass"
